# Generated by Django 3.0.6 on 2020-05-10 10:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjectapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='sche_term',
            field=models.CharField(default=1, max_length=1, verbose_name='日程学期'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='schedule',
            name='sche_datetime',
            field=models.DateField(default=datetime.datetime(2020, 5, 10, 18, 46, 36, 325858), verbose_name='日程日期'),
        ),
    ]
