# Generated by Django 3.0.6 on 2020-05-11 10:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjectapp', '0002_auto_20200510_1846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseinfo',
            name='firstdays',
        ),
        migrations.AddField(
            model_name='basicuser',
            name='firstdays',
            field=models.DateField(default=datetime.date(2020, 5, 11), verbose_name='开学第一天'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='sche_datetime',
            field=models.DateField(default=datetime.datetime(2020, 5, 11, 18, 24, 22, 62198), verbose_name='日程日期'),
        ),
    ]
