# Generated by Django 3.0.6 on 2020-05-12 10:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjectapp', '0003_auto_20200511_1824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalcourse',
            name='pcourse_times',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='sche_term',
        ),
        migrations.AddField(
            model_name='personalcourse',
            name='pcourse_len',
            field=models.CharField(default=2, max_length=4, verbose_name='一节课的长度'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalcourse',
            name='pcourse_time',
            field=models.CharField(default=1, max_length=16, verbose_name='课程是第几节'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='sche_week_num',
            field=models.CharField(default='星期一', max_length=6, verbose_name='周几'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='basicuser',
            name='firstdays',
            field=models.DateField(default=datetime.date(2020, 5, 12), verbose_name='开学第一天'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='sche_datetime',
            field=models.DateField(default=datetime.datetime(2020, 5, 12, 18, 5, 44, 325958), verbose_name='日程日期'),
        ),
    ]
