# Generated by Django 3.0.6 on 2020-05-13 07:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjectapp', '0004_auto_20200512_1806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseinfo',
            name='grade',
        ),
        migrations.AddField(
            model_name='courseinfo',
            name='len',
            field=models.CharField(default=2, max_length=4, verbose_name='长度'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courseinfo',
            name='time',
            field=models.CharField(default=1, max_length=4, verbose_name='第几节'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='basicuser',
            name='firstdays',
            field=models.DateField(default=datetime.date(2020, 5, 13), verbose_name='开学第一天'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='sche_datetime',
            field=models.DateField(default=datetime.datetime(2020, 5, 13, 15, 40, 27, 834582), verbose_name='日程日期'),
        ),
    ]
