# Generated by Django 3.0.6 on 2020-05-13 13:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjectapp', '0006_auto_20200513_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='sche_datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 13, 21, 27, 46, 46131), verbose_name='日程日期'),
        ),
    ]
