# Generated by Django 3.2 on 2021-04-25 13:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjectapp', '0007_auto_20200513_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicuser',
            name='firstdays',
            field=models.DateField(default=datetime.date(2021, 4, 25), verbose_name='开学第一天'),
        ),
        migrations.AlterField(
            model_name='courseinfo',
            name='school_year',
            field=models.CharField(default=2021, max_length=16, verbose_name='学年'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='sche_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 25, 21, 55, 34, 305485), verbose_name='日程日期'),
        ),
    ]
