# Generated by Django 2.0 on 2021-04-26 13:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjectapp', '0009_auto_20210426_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='sche_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 26, 21, 28, 40, 655466), verbose_name='日程日期'),
        ),
    ]
