# Generated by Django 2.0 on 2021-05-22 13:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjectapp', '0010_auto_20210426_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicuser',
            name='firstdays',
            field=models.DateField(default=datetime.date(2021, 5, 22), verbose_name='开学第一天'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='sche_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 22, 21, 58, 35, 257804), verbose_name='日程日期'),
        ),
    ]
