# Generated by Django 2.0 on 2021-05-22 14:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjectapp', '0012_auto_20210522_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseinfo',
            name='course_days',
            field=models.IntegerField(max_length=16, verbose_name='星期一～星期五'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='sche_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 22, 22, 56, 58, 663262), verbose_name='日程日期'),
        ),
    ]
