# Generated by Django 2.0 on 2021-05-22 15:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjectapp', '0014_auto_20210522_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseinfo',
            name='course_days',
            field=models.CharField(max_length=16, verbose_name='星期一～星期五'),
        ),
        migrations.AlterField(
            model_name='personalcourse',
            name='pcourse_days',
            field=models.CharField(max_length=16, verbose_name='星期一～星期五'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='sche_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 22, 23, 9, 24, 982884), verbose_name='日程日期'),
        ),
    ]
