# Generated by Django 3.2.9 on 2021-11-30 13:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjectapp', '0015_auto_20210522_2309'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='用户名')),
                ('password', models.CharField(max_length=50, verbose_name='密码')),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.AlterField(
            model_name='basicuser',
            name='firstdays',
            field=models.DateField(default=datetime.date(2021, 11, 30), verbose_name='开学第一天'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='sche_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 30, 21, 27, 8, 539319), verbose_name='日程日期'),
        ),
    ]
